/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AreaRouteImport } from './routes/_area'
import { Route as HouseRouteImport } from './routes/house'
import { Route as AreaIndexRouteImport } from './routes/_area.index'
import { Route as AreaBoardRouteImport } from './routes/_area.board'
import { Route as AArticleIdRouteImport } from './routes/a.$articleId'

const AreaRoute = AreaRouteImport.update({
  id: '/_area',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseRoute = HouseRouteImport.update({
  id: '/house',
  path: '/house',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaIndexRoute = AreaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AreaRoute,
} as any)
const AreaBoardRoute = AreaBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => AreaRoute,
} as any)
const AArticleIdRoute = AArticleIdRouteImport.update({
  id: '/a/$articleId',
  path: '/a/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AreaIndexRoute
  '/house': typeof HouseRoute
  '/board': typeof AreaBoardRoute
  '/a/$articleId': typeof AArticleIdRoute
}
export interface FileRoutesByTo {
  '/house': typeof HouseRoute
  '/board': typeof AreaBoardRoute
  '/a/$articleId': typeof AArticleIdRoute
  '/': typeof AreaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_area': typeof AreaRouteWithChildren
  '/house': typeof HouseRoute
  '/_area/board': typeof AreaBoardRoute
  '/a/$articleId': typeof AArticleIdRoute
  '/_area/': typeof AreaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/house' | '/board' | '/a/$articleId'
  fileRoutesByTo: FileRoutesByTo
  to: '/house' | '/board' | '/a/$articleId' | '/'
  id:
    | '__root__'
    | '/_area'
    | '/house'
    | '/_area/board'
    | '/a/$articleId'
    | '/_area/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AreaRoute: typeof AreaRouteWithChildren
  HouseRoute: typeof HouseRoute
  AArticleIdRoute: typeof AArticleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_area': {
      id: '/_area'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/house': {
      id: '/house'
      path: '/house'
      fullPath: '/house'
      preLoaderRoute: typeof HouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_area/': {
      id: '/_area/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AreaIndexRouteImport
      parentRoute: typeof AreaRoute
    }
    '/_area/board': {
      id: '/_area/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof AreaBoardRouteImport
      parentRoute: typeof AreaRoute
    }
    '/a/$articleId': {
      id: '/a/$articleId'
      path: '/a/$articleId'
      fullPath: '/a/$articleId'
      preLoaderRoute: typeof AArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AreaRouteChildren {
  AreaBoardRoute: typeof AreaBoardRoute
  AreaIndexRoute: typeof AreaIndexRoute
}

const AreaRouteChildren: AreaRouteChildren = {
  AreaBoardRoute: AreaBoardRoute,
  AreaIndexRoute: AreaIndexRoute,
}

const AreaRouteWithChildren = AreaRoute._addFileChildren(AreaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AreaRoute: AreaRouteWithChildren,
  HouseRoute: HouseRoute,
  AArticleIdRoute: AArticleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
